Feat/trello
MostafaNafie/laravel-with-elnemr pull request #1
Opened 2021-07-25 19:27 UTC by MostafaNafie

2021-07-25 19:35 UTC, aelnemr requested changes

2021-07-25 19:35 UTC, aelnemr commented on trello/app/Http/Controllers/BoardListsController.php
> +    public function index()
remove un-used functions

2021-07-25 19:35 UTC, aelnemr commented on trello/app/Http/Controllers/BoardListsController.php
> +    public function store(Request $request)
create new **RequestForm**  to make sure that your data valid

2021-07-25 19:35 UTC, aelnemr commented on trello/app/Http/Controllers/BoardListsController.php
> +            'name' => request()->input('name'),
why you injected `request` object and used `request` function!! search about differences

2021-07-25 19:35 UTC, aelnemr commented on trello/app/Http/Controllers/BoardListsController.php
> +        $board = Board::find($id);
try to use Repository pattern

2021-07-25 19:35 UTC, aelnemr commented on trello/app/Http/Controllers/BoardListsController.php
> +    public function edit($id)
remove un-used code

2021-07-25 19:35 UTC, aelnemr commented on trello/app/Http/Controllers/BoardListsController.php
> +    public function update(Request $request, $id)
remove un-used code

2021-07-25 19:35 UTC, aelnemr commented on trello/app/Http/Controllers/BoardListsController.php
> +    public function destroy($id)
remove un-used code

2021-07-25 19:40 UTC, MostafaNafie commented on trello/app/Http/Controllers/BoardListsController.php
> +            'name' => request()->input('name'),
Okay, I will

2021-07-25 19:46 UTC, MostafaNafie commented on trello/app/Http/Controllers/BoardListsController.php
> +            'name' => request()->input('name'),
I found that the request object is better if I want to inject a dummy request for testing purposes.
Also I think the object will be better if want want to use a custom object with custom validations.

So I think I should use the object instead of the function, right?

2021-07-25 19:47 UTC, MostafaNafie commented on trello/app/Http/Controllers/BoardListsController.php
> +    public function store(Request $request)
Okay, I will

2021-07-25 19:57 UTC, MostafaNafie commented on trello/app/Http/Controllers/BoardListsController.php
> +    public function store(Request $request)
Done

2021-07-25 20:44 UTC, MostafaNafie commented on trello/app/Http/Controllers/BoardListsController.php
> +        $board = Board::find($id);
Done

2021-07-26 13:23 UTC, aelnemr approved these changes

2021-07-26 13:24 UTC, aelnemr commented
I have some comments but we can discuss them in the session, Thank you.

2021-07-26 18:23 UTC, merged